### ISSUE TITLE
User Story 2: Create Pages for Maths Sites

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#20]
As a **teacher, I want**  to have a site with different pages that contain clear information, **so that** I can find what I need on each one.

## Acceptance Criteria:
Each page meets the requirements of the website.
    
## Tasks:

- [X] Index landing page where times tables can be easily reviewed.
- [X] Quiz page for testing children on their times tables.
- [X] About Us page, explaining who the site creators are and about the app itself, as well as where to find further information relating to the app and/or company.
