### ISSUE TITLE
Index / Landing Page

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#21]
As a **student, I want** the Home page to be easy to navigate, **so that I** do times tables in a fun and easy way.
As a **teacher, I want** the Home page to be easy to navigate, **so that I** teach multiplication in a straightforward way that appeals to children.
As a **site owner,** I want the Home page to be easy to navigate, and to use appropriate coding language to make the website useable.

## Acceptance Criteria:

1. User can navigate the page properly.
2. The buttons and maths work properly on the site.
3. The page is easy to read, the fonts and style are good-looking.
    
## Tasks:

- [x] Create the Home page.
- [X] Layout the page with HTML.
- [x] Do the proper styling with CSS to make the page easy-to-read.
- [ ] Set up the working JS code for the multiplication functions (where applicable).

**Comment by Borys-777** [comment]
As a USER (child), I want the Home page to be easy to navigate, so that I do maths - multiplication in a fun and easy way.

Acceptance Criteria:
1. User can navigate the page properly.
2. The buttons and maths work properly on the site. 
3. The page is easy to read, the fonts and style are good-looking.

Tasks:

1. Create the Home page.
2. Do the proper styling with CSS to make the page easy-to-read.
3. Set up the working JS code for the multiplication functions.
