### ISSUE TITLE
Quiz Page

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#22]
As a **student, I want** the Quiz page to be easy to navigate, **so that I can** interact and have fun with the Time Tables Quiz.
As a **teacher, I want** the Quiz page to be easy to navigate, **so that I can** use the Time Tables Quiz with my students in a fun and easy way.
As a **teacher, I want** the Quiz page to be easy to use, **so that users** can load and interact with the JavaScript game with no errors.

## Acceptance Criteria:

1. User can navigate the page properly.
2. The buttons and maths work properly on the site.
3. The page is easy to read, the fonts and style are good-looking.

## Tasks:

- [X] Create the Quiz page.
- [X] Layout the site with HTML.
- [x] Do the proper styling with CSS to make the page easy-to-read.
- [x] Set up the working JS code for the multiplication functions.

**Comment by Borys-777** [comment]
As a USER (child), I want the Quiz page to be easy to navigate, so that I do Time Tables Quiz- in a fun and easy way.

Acceptance Criteria:

1. User can navigate the page properly.
2. The buttons and maths work properly on the site.
3. The page is easy to read, the fonts and style are good-looking.

**Tasks:**

1. Create the Quiz page.
2. Do the proper styling with CSS to make the page easy-to-read.
3. Set up the working JS code for the multiplication functions.
