### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#23]
- As a **student, I want** the About Us page to be easy to navigate and informative, **so I can** learn more about the people who made Magical Math Monkey.
- As a **teacher, I want** the About Us page to be easy to navigate and informative, **so I can** learn about future updates that will be of use to me.
- As a **site owner, I want** the About Us page to be easy to navigate and informative, **so I can** link visitors to our social media sites.
- As a **site owner, I want** a newsletter option, **so that my visitors can** easily sign up their email address to receive future update information.

## Acceptance Criteria:

1. User can navigate the page easily.
2. There is description in the "Who Are The Bootcamp Bandits?" section.
3. There is description in the "Coming Soon! (Future Updates)" section.
4. The "Follow us" section provides the links to social media.
5. There is a form at the bottom of the page available, so the user can leave his email address.

    
## Tasks:

- [X] Create the About us page.
- [x] Do the proper styling with CSS to make the page easy-to-read.
- [X] Add content to the "Who Are The Bootcamp Bandits?" section
- [x] Add content to the "Coming Soon! (Future Updates)" section.
- [x] Add the links to social media to the "Follow us" section.
- [x] Add the form at the bottom of the page, so the user can leave his email address.

**Comment by Borys-777** [comment]
As a USER (child), I want the About Us page to be easy to navigate and informative, so I can get the important information here.

**Acceptance Criteria:**

1. User can navigate the page easily.
2. There is description in the "Who Are The Bootcamp Bandits?" section.
3. There is description in the "Coming Soon! (Future Updates)" section. 
4. The "Follow us" section provides the links to social media.
5. There is a form at the bottom of the page available, so the user can leave his email address. 

**Tasks:**

1. Create the About us page.
2. Do the proper styling with CSS to make the page easy-to-read.
3. Add content to the "Who Are The Bootcamp Bandits?" section.
4. Add content to the "Coming Soon! (Future Updates)" section. 
5.  Add the links to social media to the "Follow us" section. 
6. Add the form at the bottom of the page, so the user can leave his email address.
