### ISSUE TITLE
Add CSS to html

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#24]
As a **student, I want** the website to be easy and pleasant to read, **so that I can** have a great user experience.
As a **student, I want** the website to be easy and pleasant for my students to read, **so that I can** teach them their times tables easily.

## Acceptance Criteria:

1. The user stays on the Home page and gets a great experience using it.

    
## Tasks:

- [x] The Home page has the correct CSS with the proper colors and styles.
- [x] The Quiz page has the correct CSS with the proper colors and styles.
- [x] The About Us page has the correct CSS with the proper colors and styles.

**Comment by Borys-777** [comment]
As a USER (child), I want the Home page to be easy and pleasant to read, so that I can have a great user experience.

**Acceptance Criteria:**
1. The user stays on the Home page and gets a great experience using it.

**Tasks:** 
1. The page has the correct CSS with the proper colors and styles.
