### ISSUE TITLE
Add Bootstrap to make pages dynamic

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#25]
As **a student, I want** to be able to easily use the website **so I can** interact with all the pages.
As **the site owner, I want** all the pages on the website to be dynamic and easy to navigate.

## Acceptance Criteria:

1. User can navigate all the pages easily.
2. The site is responsive on all devices. 

## Tasks:

- [X] Add the Bootstrap containers to all the pages.
- [x] Add Bootstrap buttons with different colors and sizes where applicable.
- [x] Align the content on the pages to the center, using Bootstrap functionality.

**Comment by Borys-777** [comment]
As a USER (child), I want all the pages on the website to be dynamic and easy to navigate

**Acceptance Criteria:**
User can navigate all the pages easily.

**Tasks:**

1. Add the Bootstrap containers to all the pages.
2. Add the Bootstrap buttons with different colors and sizes. 
3. Align the content on the pages to the center, using Bootstrap functionality.
