### ISSUE TITLE
Functional Quiz using JavaScript

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#26]
As a student, I want the Magical Maths Monkey Quiz on the Quiz page to be interactive, so I can practice maths and multiplication.

## Acceptance Criteria:

1. User can use Magical Maths Monkey Quiz on the Quiz page properly
2. The JavaScript code is functional and presents the expected results.

    
## Tasks:

- [X] Add the Magical Maths Monkey Quiz on the Quiz page.
- [x] Set the proper JS code and functonality on this page.
- [x] Ensure that the multiplication function provide the correct numbers and results.
- [x] Ensure the pop-up windows for the correct and incorrect answers are properly displayed.

**Comment by Borys-777** [comment]
As a USER (child), I want the Magical Maths Monkey Quiz on the Quiz page to be interactive, so I can practice maths and multiplication.

**Acceptance Criteria:**
User can use Magical Maths Monkey Quiz on the Quiz page properly, anfd the JS code is correct. 

**Tasks:**

1. Add the Magical Maths Monkey Quiz on the Quiz page.
2. Set the proper JS code and functonality on this page. 
3. Ensure that the multiplication function provide the correct numbers and results.
4. Ensure the pop-up windows for the correct and incorrect answers are properly displayed.
