### ISSUE TITLE
Add Update Newsletter Signup

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#27]
As **a teacher, I want** to be able to input my email address into a newsletter sign-up form, **so that I can** follow the most recent updates for Magical Maths Monkey.

## Acceptance Criteria:
User can add the email address into the form. And the form works properly (sends the data to the server).
    
## Tasks:

- [X] Add the form at the bottom of the About Us page.
- [x] Ensure the user can input the email address (and not only the numbers) - field should be set to the "email address type".
- [ ] The email should be collected and sent to the server.

**Comment by Borys-777** [comment]
As a USER (child), I want to be able to input my email address into the form, so that I can follow up with the most recent updates.

**Acceptance Criteria:**
User can add the email address into the form. And the form works properly (sends the data to the server).

**Tasks:**

1. Add the form at the bottom of the About Us page.
2. Ensure the user can input the email address (and not only the numbers) - field should be set to the "email address type".
3. The email should be collected and sent to the server.
