### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#28]
As **a site visitor, I want** to be able to be able to easily navigate through the website, using the buttons at the top of the page.

## Acceptance Criteria:

- User can click the buttons at the top of the page ("Home, Quiz, About us"), and they redirect to the correct pages.

    
## Tasks:

- [X] Create the navigation buttons ("Home, Quiz, About us").
- [x] The buttons should be active and redirecting to the relevant pages.
- [x] The navigation bar should be responsive for mobile platform viewing.

**Comment by Borys-777** [comment]
As a USER (child), I want to be able to be able to easily navigate through the website, using the buttons at the top of the page.

**Acceptance Criteria:**
User can click the buttons at the top of the page ("Home, Quiz, About us"), and they redirect to the correct pages. 

**Tasks:**

1. Create the navigation buttons ("Home, Quiz, About us").
2. The buttons should be active and redirecting to the relevant pages.
