### ISSUE TITLE
Create a Read.me document

### ISSUE THREAD

**Issue by Borys-777** [Stephen-Bevan/Magical-Maths-Monkey#42]
As a site owner, I would like to have the Read.me document, with all the required information about the website. 

**Acceptance Criteria:**
The Read.me document is fully completed and all the required sections are filled in.

**Tasks:**

- [x] Add description and Success Metrics to Read.me doc.
- [x] Add the information about planned features and existing features
- [x] Add the information about Testing, Validation Testing, Unfixed bugs (if required) 
- [x] Add the information to Media and Content sections
